import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, Bell, ChevronDown, Play, Plus, Film, LayoutDashboard, Library, Users, Settings, ArrowUpRight, MoreHorizontal, Clock3, CheckCircle2, UploadCloud, GripVertical, MonitorPlay, SlidersHorizontal, Sparkles, Menu, X, ChevronUp, ChevronDown as ChevronDownIcon } from 'lucide-react';
import './styles.css';
import { beginVdocipherUpload, heartbeatPlayback, releasePlayback, requestPlayback, signInWithOAuth, supabase } from './lib/supabase.js';
import { getInstallationId } from './lib/platform-contract.js';

const seed = [
  { title:'La última frontera', genre:'Ciencia ficción · 2025', id:'vdo_78324', status:'Publicado', date:'Hoy, 10:42', image:'photo-1462331940025-496dfbfc7564', color:'#7461c6', duration:'2 h 08 min' },
  { title:'Donde nace el mar', genre:'Drama · 2024', id:'vdo_61905', status:'Publicado', date:'Ayer, 16:18', image:'photo-1518837695005-2083093ee35b', color:'#277e83', duration:'1 h 52 min' },
  { title:'Los días de abril', genre:'Thriller · 2025', id:'vdo_90317', status:'Procesando', date:'Ayer, 12:06', image:'photo-1500530855697-b586d89ba3ee', color:'#89694e', duration:'1 h 46 min' },
  { title:'Atlas de lo invisible', genre:'Documental · 2023', id:'vdo_28441', status:'Publicado', date:'12 oct, 09:30', image:'photo-1534447677768-be436bb09401', color:'#5f7185', duration:'52 min' },
  { title:'Una casa en invierno', genre:'Drama · 2024', id:'vdo_55102', status:'Borrador', date:'10 oct, 14:55', image:'photo-1470770841072-f978cf4d019e', color:'#799487', duration:'1 h 38 min' },
];
const url = (id,w=700) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
const toroArt = `${import.meta.env.BASE_URL}images/festejo-hero.png`;
function CustomerHome({ session, onSignIn, notify, query, setQuery }) {
 const [catalog,setCatalog]=useState([]); const [player,setPlayer]=useState(null); const [tab,setTab]=useState('Inicio'); const [saving,setSaving]=useState(false);
 const platform=window.PalmSystem?'lg_webos':window.tizen?'samsung_tizen':'web';
 useEffect(()=>{if(!supabase)return;supabase.from('content').select('*').eq('status','published').contains('visibility',[platform]).order('sort_order').then(({data})=>{if(data?.length)setCatalog(data.map(x=>({id:x.vdocipher_id,title:x.title,genre:x.genre||'Festejo',poster:x.poster_url,hero:x.hero_url,duration:x.duration_seconds?`${Math.round(x.duration_seconds/60)} min`:'A la carta',synopsis:x.synopsis||''})))});},[platform]);
 const contents=catalog.length?catalog:[
  {id:'demo-live',title:'Feria de San Isidro · Madrid',genre:'DIRECTO · LAS VENTAS',poster:toroArt,duration:'EN DIRECTO',synopsis:'La emoción de Madrid, en vivo desde la plaza de toros de Las Ventas.'},
  {id:'demo-1',title:'La tarde de los sueños',genre:'MADRID · 2025',poster:toroArt,duration:'2 h 14 min'},
  {id:'demo-2',title:'Sevilla: una feria para el recuerdo',genre:'SEVILLA · 2025',poster:toroArt,duration:'2 h 32 min'},
  {id:'demo-3',title:'Roca Rey: el valor de una tarde',genre:'DOCUMENTAL · 2024',poster:'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=85',duration:'48 min'},
  {id:'demo-4',title:'Pamplona desde dentro',genre:'REPORTAJE · 2024',poster:'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=85',duration:'36 min'},
  {id:'demo-5',title:'El arte de la faena',genre:'SERIE ORIGINAL · 2025',poster:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=85',duration:'6 episodios'},
 ];
 useEffect(()=>{const onKey=(event)=>{if(!['ArrowRight','ArrowLeft','ArrowUp','ArrowDown'].includes(event.key))return;const nodes=[...document.querySelectorAll('.toro-app button:not([disabled]), .toro-app a[href]')].filter(node=>node.getClientRects().length>0);const current=document.activeElement;const index=nodes.indexOf(current);if(index<0){nodes[0]?.focus();return}const rect=current.getBoundingClientRect();const candidates=nodes.map((node,i)=>({node,i,r:node.getBoundingClientRect()})).filter(x=>x.i!==index&&({ArrowRight:x.r.left>=rect.right-8,ArrowLeft:x.r.right<=rect.left+8,ArrowDown:x.r.top>=rect.bottom-8,ArrowUp:x.r.bottom<=rect.top+8}[event.key]));if(!candidates.length)return;const horizontal=event.key==='ArrowLeft'||event.key==='ArrowRight';candidates.sort((a,b)=>{const ac=horizontal?Math.abs(a.r.top-rect.top)*2+Math.abs(a.r.left-rect.left):Math.abs(a.r.left-rect.left)*2+Math.abs(a.r.top-rect.top);const bc=horizontal?Math.abs(b.r.top-rect.top)*2+Math.abs(b.r.left-rect.left):Math.abs(b.r.left-rect.left)*2+Math.abs(b.r.top-rect.top);return ac-bc});event.preventDefault();candidates[0].node.focus()};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 const start=async(item)=>{if(item.id.startsWith('demo-')){notify('Conecta Supabase y publica este título para reproducirlo.');return}if(!session){onSignIn();return}setSaving(true);try{const embed=await requestPlayback(item.id,getInstallationId(platform));setPlayer({item,embed})}catch(error){notify(error.message||'No se pudo iniciar la reproducción.')}finally{setSaving(false)}};
 useEffect(()=>{if(!player)return;const deviceId=getInstallationId(platform);const heartbeat=setInterval(()=>heartbeatPlayback(deviceId).catch(()=>{}),30000);return()=>{clearInterval(heartbeat);releasePlayback(deviceId).catch(()=>{})}},[player,platform]);
 const closePlayer=()=>setPlayer(null); const visible=contents.filter(c=>`${c.title} ${c.genre}`.toLowerCase().includes(query.toLowerCase()));
 const rail=(title,items)=> <section className="toro-rail"><div className="toro-rail-head"><h2>{title}</h2><button onClick={()=>setTab('A la carta')}>Ver todos <ArrowUpRight size={15}/></button></div><div className="toro-cards">{items.map((item,i)=><button className="toro-card" key={item.id} onClick={()=>start(item)}><span className="toro-poster" style={{backgroundImage:`linear-gradient(0deg,#08090de8 0%,transparent 65%),url(${item.poster||toroArt})`}}><i>{String(i+1).padStart(2,'0')}</i><b className={item.duration==='EN DIRECTO'?'onair':''}>{item.duration}</b><span className="toro-hover-play"><Play fill="currentColor" size={17}/></span></span><strong>{item.title}</strong><small>{item.genre}</small></button>)}</div></section>;
 return <div className="toro-app">
  <header className="toro-header"><a className="toro-logo" href="#inicio" onClick={e=>{e.preventDefault();setTab('Inicio')}}><span>U</span> UMBRAL<small>TV</small></a><nav>{['Inicio','En directo','A la carta','Programas'].map(n=><button key={n} className={tab===n?'selected':''} onClick={()=>setTab(n)}>{n}</button>)}</nav><div className="toro-tools"><label><Search size={17}/><input aria-label="Buscar festejos" placeholder="Buscar" value={query} onChange={e=>setQuery(e.target.value)}/></label>{session?<button className="toro-account" title={session.user.email}><span>{session.user.email.slice(0,1).toUpperCase()}</span></button>:<button className="toro-login" onClick={onSignIn}>Iniciar sesión</button>}<button className="toro-admin-link" onClick={()=>window.dispatchEvent(new CustomEvent('open-admin'))}>Panel editorial</button></div></header>
  {tab==='Panel'?<div className="toro-admin-prompt"><span className="toro-live-pill">UMBRAL · STUDIO</span><h1>Gestiona tus contenidos.</h1><p>El panel editorial está disponible en la vista de administración.</p><button onClick={()=>window.dispatchEvent(new CustomEvent('open-admin'))}>Abrir panel</button></div>:<>
   <section className="toro-feature" style={{backgroundImage:`linear-gradient(90deg,#090a0deF 0%,#090a0dbf 37%,#090a0d25 74%),linear-gradient(0deg,#090a0d 0%,transparent 44%),url(${toroArt})`}}><div className="toro-feature-content"><span className="toro-live-pill"><i/> PRÓXIMO DIRECTO</span><p className="toro-kicker">SÁBADO · 18:30 · LAS VENTAS</p><h1>La emoción<br/>vuelve a Madrid.</h1><p className="toro-description">Vive cada pase, cada instante y toda la pasión de la Feria de San Isidro.</p><div className="toro-cta"><button className="toro-primary" onClick={()=>start(contents[0])}><Play size={17} fill="currentColor"/>Ver festejo</button><button className="toro-secondary" onClick={()=>setTab('A la carta')}>Explorar programación</button></div></div><div className="toro-feature-foot"><span>UNA PLAZA. TODA LA PASIÓN.</span><div><i className="active"/><i/><i/><i/></div></div></section>
   <div className="toro-content">{tab==='Inicio'?<><section className="toro-live-strip"><div className="toro-live-mark"><i/>EN DIRECTO</div><div><b>Canal Umbral</b><span>La televisión taurina · Programación 24 h</span></div><button onClick={()=>start(contents[0])}>Ver canal <ArrowUpRight size={15}/></button></section>{rail('En cartelera',visible.slice(0,4))}{rail('Festejos para volver a vivir',visible.slice(1,5))}<section className="toro-editorial"><div><span>HECHO PARA LOS QUE SIENTEN LA PLAZA</span><h2>El arte está en cada detalle.</h2><p>Festejos, historias y voces que mantienen viva la pasión.</p></div><button onClick={()=>setTab('Programas')}>Descubrir Umbral <ArrowUpRight size={15}/></button></section>{rail('Originales Umbral',visible.slice(2,6))}</>:<><div className="toro-page-title"><span>UMBRAL TV · PROGRAMACIÓN</span><h1>{tab}</h1><p>Festejos en directo y a la carta, desde las grandes plazas.</p></div>{rail(tab==='En directo'?'Ahora y próximamente':'Todo el catálogo',visible)}</>}</div>
  </>}
  {player&&<div className="toro-player"><div className="toro-player-bar"><button onClick={closePlayer}>← Volver</button><strong>{player.item.title}</strong><button onClick={closePlayer}>✕</button></div><iframe title={player.item.title} src={`https://player.vdocipher.com/v2/?otp=${encodeURIComponent(player.embed.otp)}&playbackInfo=${encodeURIComponent(player.embed.playbackInfo)}`} allow="encrypted-media;autoplay;fullscreen" allowFullScreen/> </div>}
  {saving&&<div className="toro-loading"><span/>Preparando reproducción segura…</div>}
 </div>
}
function App(){
 const [section,setSection]=useState('Resumen'); const [admin,setAdmin]=useState(false); const [items,setItems]=useState(seed); const [query,setQuery]=useState(''); const [modal,setModal]=useState(false); const [toast,setToast]=useState(''); const [mobileNav,setMobileNav]=useState(false); const [session,setSession]=useState(null);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,current)=>setSession(current));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{const open=()=>setAdmin(true);window.addEventListener('open-admin',open);return()=>window.removeEventListener('open-admin',open)},[]);
 useEffect(()=>{if(!supabase||session?.user?.app_metadata?.role!=='admin')return;supabase.from('content').select('*').order('sort_order').then(({data,error})=>{if(error){notify(error.message);return}if(data)setItems(data.map(x=>({title:x.title,genre:x.genre||'Sin categoría',id:x.vdocipher_id,status:({published:'Publicado',processing:'Procesando',draft:'Borrador',failed:'Error'})[x.status]||x.status,date:new Date(x.updated_at||x.created_at).toLocaleDateString('es-ES'),image:x.poster_url?null:'photo-1485846234645-a62644f84728',poster:x.poster_url,sortOrder:x.sort_order})))});},[session]);
 const notify=(m)=>{setToast(m);setTimeout(()=>setToast(''),2800)};
 const moveContent=async(index,delta)=>{const next=[...items];const target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setItems(next);if(supabase&&session?.user?.app_metadata?.role==='admin'){const writes=next.map((entry,sort_order)=>supabase.from('content').update({sort_order}).eq('vdocipher_id',entry.id));const results=await Promise.all(writes);const failed=results.find(result=>result.error);if(failed)notify(failed.error.message);else notify('Orden guardado y compartido con las plataformas.')}else notify('Orden de previsualización actualizado.')};
 const save=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const title=f.get('title')||'Nuevo estreno';const file=f.get('video');
  if(!supabase){notify('Configura Supabase para subir contenido. Consulta .env.example.');return}
  try { const created=await beginVdocipherUpload(file,title,{genre:f.get('genre'),synopsis:f.get('description')}); setItems([{title,genre:`${f.get('genre')||'Cine'} · 2026`,id:created.vdocipher_id,status:'Procesando',date:'Ahora',image:'photo-1485846234645-a62644f84728',color:'#8064b7',duration:'—'},...items]);setModal(false);notify('Vídeo subido. VdoCipher ha iniciado el procesamiento.'); }
  catch(error){notify(error.message||'No se pudo subir el vídeo.');}
 };
 const nav=[['Resumen',LayoutDashboard],['Catálogo',Library],['Colecciones',Film],['Clientes',Users],['Ajustes',Settings]];
 const filtered=items.filter(x=>x.title.toLowerCase().includes(query.toLowerCase()));
 return <div className={`app-shell ${admin?'admin-mode':'customer-mode'}`}>
  <aside className={`sidebar ${mobileNav?'open':''}`}><div className="brand"><div className="brand-mark"><span/></div><div><b>umbral</b><small>OTT STUDIO</small></div><button className="close-nav" onClick={()=>setMobileNav(false)}><X size={18}/></button></div>
   <div className="workspace-label">WORKSPACE</div><button className="workspace"><span className="workspace-icon">U</span><span><b>Umbral Films</b><small>Plan profesional</small></span><ChevronDown size={15}/></button>
   <div className="nav-label">PLATAFORMA</div><nav>{nav.map(([n,I])=><button key={n} onClick={()=>{setSection(n);setMobileNav(false)}} className={`nav-item ${section===n?'active':''}`}><I size={18}/><span>{n}</span>{n==='Catálogo'&&<span className="nav-count">{items.length}</span>}</button>)}</nav>
   <div className="sidebar-bottom"><div className="usage-card"><div className="usage-title"><span>Almacenamiento</span><span>68%</span></div><div className="meter"><i/></div><small>1,36 TB de 2 TB utilizados</small><button onClick={()=>notify('Próximamente: gestión de tu plan')}>Gestionar plan <ArrowUpRight size={13}/></button></div><div className="profile"><div className="avatar">MC</div><div><b>María Cruz</b><small>Administradora</small></div><MoreHorizontal size={19}/></div></div>
  </aside>
  {mobileNav&&<div className="scrim" onClick={()=>setMobileNav(false)}/>}
  <main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobileNav(true)}><Menu/></button><div className="crumb">Plataforma <span>/</span> <b>{section}</b></div><div className="top-actions"><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar en el catálogo"/><kbd>⌘ K</kbd></label><button className="icon-btn" onClick={()=>notify('No tienes notificaciones nuevas')}><Bell size={18}/><i/></button><div className="divider"/>{!admin&&(session?<span className="signed-user">{session.user.email}</span>:<button className="view-switch" onClick={async()=>{try{const {error}=await signInWithOAuth('google');if(error)throw error}catch(error){notify(error.message)}}}><Users size={15}/>Entrar</button>)}<button className="view-switch" onClick={()=>setAdmin(!admin)}><MonitorPlay size={15}/>{admin?'Vista cliente':'Panel admin'}<ChevronDown size={14}/></button></div></header>
   <div className="content">{admin&&<div className="welcome-row"><div><div className="eyebrow"><span className="live-dot"/> UMBRAL · STUDIO</div><h1>Tu contenido, bajo control.</h1><p>Gestiona el catálogo que verán tus espectadores.</p></div><button className="primary-btn" onClick={()=>setModal(true)}><Plus size={17}/>Subir contenido</button></div>}{!admin&&<CustomerHome session={session} onSignIn={async()=>{try{const {error}=await signInWithOAuth('google');if(error)throw error}catch(error){notify(error.message)}}} notify={notify} query={query} setQuery={setQuery}/>}
   {admin&&<><div className="demo-note">Vista de previsualización · Las métricas y títulos de ejemplo se reemplazarán al conectar el catálogo de Supabase.</div><div className="stats"><div className="stat-card"><span>CONTENIDOS</span><strong>{items.length+124}</strong><small><b>+8</b> este mes</small><div className="stat-icon purple"><Film size={17}/></div></div><div className="stat-card"><span>REPRODUCCIONES</span><strong>24.8k</strong><small><b>↑ 12,4%</b> vs. mes anterior</small><div className="stat-icon green"><Play size={16}/></div></div><div className="stat-card"><span>CLIENTES ACTIVOS</span><strong>3.204</strong><small><b>+186</b> últimos 30 días</small><div className="stat-icon amber"><Users size={17}/></div></div><div className="stat-card"><span>MINUTOS VISTOS</span><strong>86.2k</strong><small>Media <b>42 min</b> por sesión</small><div className="stat-icon blue"><Clock3 size={17}/></div></div></div>
  <section className="management"><div className="section-heading"><div><div className="eyebrow">TU BIBLIOTECA</div><h2>Contenido <span className="subcount">{filtered.length} títulos recientes</span></h2></div><div className="table-actions"><button className="secondary-btn" onClick={()=>notify('Filtros de catálogo listos')}><SlidersHorizontal size={15}/>Filtros</button><button className="primary-btn compact" onClick={()=>setModal(true)}><Plus size={16}/>Subir contenido</button></div></div><div className="table-wrap"><table><thead><tr><th><input type="checkbox"/></th><th>TÍTULO</th><th>VODOCIPHER ID</th><th>ESTADO</th><th>ACTUALIZADO</th><th>ORDEN</th></tr></thead><tbody>{filtered.map((item,i)=><tr key={item.id}><td><input type="checkbox"/></td><td><div className="title-cell"><span className="row-cover" style={{backgroundImage:`url(${url(item.poster||item.image,140)})`}}/><span><b>{item.title}</b><small>{item.genre}</small></span></div></td><td><code>{item.id}</code></td><td><span className={`status ${item.status.toLowerCase()}`}><i/>{item.status}</span></td><td className="date-cell">{item.date}</td><td><div className="row-order"><button aria-label="Subir título" onClick={()=>moveContent(i,-1)}><ChevronUp size={14}/></button><button aria-label="Bajar título" onClick={()=>moveContent(i,1)}><ChevronDownIcon size={14}/></button></div></td></tr>)}</tbody></table>{filtered.length===0&&<div className="empty">No encontramos títulos con “{query}”.</div>}</div><div className="table-foot">Orden de catálogo sincronizado en las plataformas <button onClick={()=>setSection('Colecciones')}>Gestionar colecciones <ArrowUpRight size={13}/></button></div></section>
   <section className="bottom-grid"><div className="activity-card"><div className="section-heading"><div><div className="eyebrow">ÚLTIMOS MOVIMIENTOS</div><h2>Actividad reciente</h2></div><button className="more"><MoreHorizontal size={18}/></button></div><div className="activity-line"><span className="activity-icon violet"><UploadCloud size={16}/></span><div><b>El último horizonte</b><small>Se ha subido un nuevo vídeo</small></div><time>hace 12 min</time></div><div className="activity-line"><span className="activity-icon mint"><CheckCircle2 size={16}/></span><div><b>Donde nace el mar</b><small>Procesamiento completado</small></div><time>hace 1 h</time></div></div><div className="platform-card"><div className="eyebrow">ESTADO DEL SERVICIO</div><h2>Todo en orden.</h2><p>Las plataformas están sincronizadas y funcionando.</p><div className="platform-list"><span>Web <i>Operativo</i></span><span>Smart TV <i>Operativo</i></span><span>iOS & Android <i>Operativo</i></span></div></div></section></>}
   <footer><span>© 2025 Umbral Films</span><span>Una plataforma para historias extraordinarias <i>✳</i></span><span>Ayuda&nbsp;&nbsp; · &nbsp;&nbsp;Estado del servicio</span></footer>
  </div></main>
  {modal&&<div className="modal-backdrop" onClick={()=>setModal(false)}><form className="upload-modal" onClick={e=>e.stopPropagation()} onSubmit={save}><button type="button" className="modal-close" onClick={()=>setModal(false)}><X size={18}/></button><div className="eyebrow">NUEVO CONTENIDO</div><h2>Sube una historia.</h2><p>El vídeo se procesará de forma segura en VdoCipher.</p><label className="dropzone"><UploadCloud size={23}/><b>Selecciona el archivo de vídeo</b><small>MP4, MOV · máximo 5 GB por subida directa</small><input type="file" accept="video/*" name="video" required/></label><label className="field">Título<input name="title" required placeholder="Nombre del contenido"/></label><label className="field">Género<select name="genre"><option>Drama</option><option>Ciencia ficción</option><option>Documental</option><option>Thriller</option><option>Comedia</option></select></label><label className="field">Descripción<textarea name="description" placeholder="Una breve sinopsis…" rows="3"/></label><div className="modal-buttons"><button type="button" className="secondary-btn" onClick={()=>setModal(false)}>Cancelar</button><button className="primary-btn"><UploadCloud size={16}/>Subir contenido</button></div></form></div>}
  {toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}</div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
